# spring:
#   data:
#     mongodb:
#       username: alaa
#       password: 12345
#       host: localhost
#       port: 27017
#       database: chat_app
#       authentication-database: admin

# server:
#   port: 8088
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat_app
server:
  port: 8088
